@baseUrl = http://localhost:3000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMzQzYzZhYzUtMmI3Mi00YzQxLWE5ZWItMjhmNWFlNDlhZjgwIiwiaWF0IjoxNjUyNzExMTAyLCJleHAiOjE2NTI3MTIwMDIsImlzcyI6InN1cHBvcnRAZGVsbGluZ3IuY29tIiwianRpIjoiY2IxMzVjMWEtY2Q5Mi00Y2IwLTk0OGEtMGQyNzBkYTljZWIxIn0.oM3cS-tWw7qo2yHnEeOBqT3goJQDs1PYu9ajzUVbjUc

########################################################################
###########                       AUTH                       ###########
########################################################################

### Authenticates a user
POST {{baseUrl}}/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "myS3cretP@55w0rd!"
}

########################################################################
###########                     DOCUMENT                     ###########
########################################################################

### Upload a document
POST {{baseUrl}}/documents HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Payment invoice
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="transactionId"

b514e04c-b3e7-4346-b9f9-41c9d66cf5e2
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="document.pdf"
Content-Type: application/pdf

< ./test/utils/files/invoice.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

########################################################################
###########                      HEALTH                      ###########
########################################################################

### Get health status
GET {{baseUrl}}/health HTTP/1.1
Accept: application/json
Content-Type: application/json

########################################################################
###########                   TRANSACTION                    ###########
########################################################################

### Get transaction
GET {{baseUrl}}/transaction/b514e04c-b3e7-4346-b9f9-41c9d66cf5e2 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a new transaction
POST {{baseUrl}}/transactions HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "amount": 10,
  "reference": "Add 10 Dollars",
  "type": "credit",
  "walletId": "2103b97d-2204-440c-aced-e9b3cb38a8c6"
}


########################################################################
###########                       USER                       ###########
########################################################################

### Get the authenticated user's profile
GET {{baseUrl}}/user HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Delete the authenticated user's account
DELETE {{baseUrl}}/user HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Register a new user
POST {{baseUrl}}/users/registration HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "jane.doe@example.com",
  "password": "myS3cretP@55w0rd!"
}

########################################################################
###########                     WALLET                       ###########
########################################################################

### Get wallet
GET {{baseUrl}}/wallet/2103b97d-2204-440c-aced-e9b3cb38a8c6 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a new wallet
POST {{baseUrl}}/wallets HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Secondary"
}
