@baseUrl = http://localhost:3000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMzQzYzZhYzUtMmI3Mi00YzQxLWE5ZWItMjhmNWFlNDlhZjgwIiwiaWF0IjoxNjQzMjk4Njc0LCJleHAiOjE2NDMyOTk1NzQsImlzcyI6InN1cHBvcnRAZGVsbGluZ3IuY29tIiwianRpIjoiMjBkOWEzYTctNWFiMS00MWZjLThlYWEtYjk1ODg1OTEyMTAxIn0.xZAN6xKeBgK8SuV3u-XYXkkoeOByJaolLOl6Zjs3-kg

########################################################################
###########                       AUTH                       ###########
########################################################################

### Authenticates a user
POST {{baseUrl}}/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "myS3cretP@55w0rd!"
}

########################################################################
###########                      HEALTH                      ###########
########################################################################

### Get health status
GET {{baseUrl}}/health HTTP/1.1
Accept: application/json
Content-Type: application/json

########################################################################
###########                   TRANSACTION                    ###########
########################################################################

### Get transaction
GET {{baseUrl}}/transaction/b514e04c-b3e7-4346-b9f9-41c9d66cf5e2 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a new transaction
POST {{baseUrl}}/transactions HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "amount": 10,
  "reference": "Add 10 Dollars",
  "type": "credit",
  "walletId": "2103b97d-2204-440c-aced-e9b3cb38a8c6"
}


########################################################################
###########                       USER                       ###########
########################################################################

### Get the authenticated user's profile
GET {{baseUrl}}/user HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Delete the authenticated user's account
DELETE {{baseUrl}}/user HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Register a new user
POST {{baseUrl}}/users/registration HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "jane.doe@example.com",
  "password": "myS3cretP@55w0rd!"
}

########################################################################
###########                     WALLET                       ###########
########################################################################

### Get wallet
GET {{baseUrl}}/wallet/2103b97d-2204-440c-aced-e9b3cb38a8c6 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a new wallet
POST {{baseUrl}}/wallets HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Secondary"
}
