@baseUrl = http://localhost:3000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMzQzYzZhYzUtMmI3Mi00YzQxLWE5ZWItMjhmNWFlNDlhZjgwIiwiaWF0IjoxNjQzMjA4MTM4LCJleHAiOjE2NDMyMDkwMzgsImlzcyI6InN1cHBvcnRAZGVsbGluZ3IuY29tIiwianRpIjoiMzgzYWMyOTMtZGM0OS00NTBhLWFiNTEtZTY5ZGJlMjgzMTllIn0.nFyuEvhTu9l3cDWDWoaCVel5n43UppVYY-2t2YbCYE0

########################################################################
###########                       AUTH                       ###########
########################################################################

### Authenticates a user
POST {{baseUrl}}/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "myS3cretP@55w0rd!"
}

########################################################################
###########                      HEALTH                      ###########
########################################################################

### Get health status
GET {{baseUrl}}/health HTTP/1.1
Accept: application/json
Content-Type: application/json

########################################################################
###########                   TRANSACTION                    ###########
########################################################################

### Get transaction
GET {{baseUrl}}/transaction/699c003c-8157-41c4-b6d1-29ff318c73a3 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

########################################################################
###########                       USER                       ###########
########################################################################

### Get the authenticated user's profile
GET {{baseUrl}}/user HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Delete the authenticated user's account
DELETE {{baseUrl}}/user HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Register a new user
POST {{baseUrl}}/users/registration HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "myS3cretP@55w0rd!"
}

########################################################################
###########                     WALLET                       ###########
########################################################################

### Get wallet
GET {{baseUrl}}/wallet/2103b97d-2204-440c-aced-e9b3cb38a8c6 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a new wallet
POST {{baseUrl}}/wallet HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Secondary"
}
